### ISSUE TITLE
harms more than help?

### ISSUE THREAD

**Issue by gcb** [kethinov/no-cli-ads#2]
Why not motivate people to fork with nothing but a patch that removes the ad?

that would be more helpful to open source as everyone can then point to the advertising-free version and send a very clear message to the original maintainer.

**Comment by Johannestegner** [comment]
As of right now, I kind of agree, but if ads in packages becomes a standard, we aught to start using something like this.

The idea of forking and removing the ad is okay for top level packages, but if it's a dependency of a dependency, it will force you to fork a whole lot of projects to remove the ads.

This should be something that npm should take care of  though...

**Comment by Simonwep** [comment]
I totally agree @Johannestegner This, is a terrible idea. Assume a project with ~1000 deps, and everyone prints smth to the console. Your logs, your ci - everything get's totally messed up.

**Comment by kethinov** [comment]
It's a big, beautiful world. People will push back against stuff they find unacceptable in their own ways. Some people did attempt to fork the project in protest. Others said lots of vicious and toxic things to the package author in that [now infamous issue thread](https://github.com/standard/standard/issues/1381).

Ultimately, I think my response to it is [taking the high road](https://github.com/feross/funding/issues/4#issuecomment-523700261) in comparison to all that. I don't want to see the project forked or the community splinter off into factions. I do want to see the author get paid. But we also need to draw a line against unacceptable forms of monetization. Doing that helps us find the acceptable kinds.

In the end, it had an impact. The author has been paying attention. The latest version of `funding` now supports disabling the ads via environment variable: `export OPEN_SOURCE_CONTRIBUTOR=true`. Given that, I don't see the harm here. Looks like it helped to me.

**Comment by adrianhopebailie** [comment]
> The latest version of funding now supports disabling the ads via environment variable: export OPEN_SOURCE_CONTRIBUTOR=true.

So is the next version of this package going to stop needing to spawn processes and watch my filesystem and simply set `OPEN_SOURCE_CONTRIBUTOR=true`?

**Comment by gcb** [comment]
Good point on the deep dependency problem. I guess forking and having everyone using the fork (which by definition is more trustworthy just by the fact they do not include advertisement) is fine for the major projects, but goes out of the window when `ltrim` or something starts to include advertisement.
